project:
  type: website

format:
  html:
    theme: bootstrap
    css: styles.css
    toc: true

website:
  twitter-card:
     creator: "@eliasdabbas"
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
  sidebar:
    style: floating
  google-analytics: "G-N2M6ZCQTX5"

metadata-files: [nbdev.yml, sidebar.yml]